name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk

      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "platform-tools"
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab
