name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools latest
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk

      - name: Install SDK packages
        run: |
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          sdkmanager --version
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Prepare Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/*.aab

      - name: Set Release Tag
        id: tag
        run: |
          # Start from 101 if first release
          START=101

          # Get the last release tag number, default v100 if none exists
          LAST_TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName' 2>/dev/null || echo "v100")

          # Extract numeric part
          LAST_NUM=$(echo $LAST_TAG | grep -oE '[0-9]+')

          # Increment
          NEXT_NUM=$((LAST_NUM + 1))
          echo "NEXT_TAG=v$NEXT_NUM"
          echo "NEXT_TAG=v$NEXT_NUM" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.NEXT_TAG }}
          name: Release ${{ env.NEXT_TAG }}
          draft: false
          prerelease: false
          token: ${{ secrets.REPO_PAT }}

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: app/build/outputs/apk/release/*.apk
          tag_name: ${{ env.NEXT_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}

      - name: Upload AAB to GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: app/build/outputs/bundle/release/*.aab
          tag_name: ${{ env.NEXT_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
