name: Build Android App

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_ALIAS:    ${{ secrets.KEYSTORE_ALIAS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            mkdir -p app
            echo "$KEYSTORE_BASE64" | base64 --decode > app/release.keystore
            echo "KEYSTORE=$PWD/app/release.keystore" >> $GITHUB_ENV
          else
            echo "No KEYSTORE_BASE64 secret provided; signing will fail if required."
            exit 1
          fi

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -sSLo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk.zip -d latest
          rm sdk.zip
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK 35 (clean)
        run: |
          yes | sdkmanager --licenses
          rm -rf $ANDROID_SDK_ROOT/platforms/android-35 || true
          sdkmanager --uninstall "platforms;android-35" || true
          sdkmanager --uninstall "build-tools;35.0.0" || true
          sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Install Gradle 8.7
        run: |
          GRADLE_VER=8.7
          mkdir -p $HOME/gradle-dist
          curl -sSLo gradle.zip https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip
          unzip -q gradle.zip -d $HOME/gradle-dist
          GRADLE_HOME=$(ls -d $HOME/gradle-dist/gradle-* | head -n1)
          echo "GRADLE_HOME=$GRADLE_HOME" >> $GITHUB_ENV
        shell: bash

      - name: Build Debug APK
        run: $GRADLE_HOME/bin/gradle --no-daemon assembleDebug

      - name: Build Release AAB
        run: $GRADLE_HOME/bin/gradle --no-daemon bundleRelease

      - name: Upload APK & AAB (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: atrack-manager-builds
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/release/*.aab

      - name: Create GitHub Release (attach APK + AAB)
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "aTrack Manager Build ${{ github.run_number }}"
          body: "Automated build of aTrack Manager (APK + AAB)."
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
